// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeNDmBUyzGyG4c8_qwFcF5c3YYyUXNcoU',
    appId: '1:724636203630:web:114fa136d92101ef7d847f',
    messagingSenderId: '724636203630',
    projectId: 'benevolentrealty-cfb1d',
    authDomain: 'benevolentrealty-cfb1d.firebaseapp.com',
    storageBucket: 'benevolentrealty-cfb1d.firebasestorage.app',
    measurementId: 'G-6NH5W6CS6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9W2KhnFcLroVCoAizbq4w7rpe5izHck',
    appId: '1:724636203630:android:2bdb2319a8fade157d847f',
    messagingSenderId: '724636203630',
    projectId: 'benevolentrealty-cfb1d',
    storageBucket: 'benevolentrealty-cfb1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gfdxF4yObNjCH5925finiOot30HppaM',
    appId: '1:724636203630:ios:b7b588cbd10b56787d847f',
    messagingSenderId: '724636203630',
    projectId: 'benevolentrealty-cfb1d',
    storageBucket: 'benevolentrealty-cfb1d.firebasestorage.app',
    iosBundleId: 'com.benevolent.crmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gfdxF4yObNjCH5925finiOot30HppaM',
    appId: '1:724636203630:ios:b7b588cbd10b56787d847f',
    messagingSenderId: '724636203630',
    projectId: 'benevolentrealty-cfb1d',
    storageBucket: 'benevolentrealty-cfb1d.firebasestorage.app',
    iosBundleId: 'com.benevolent.crmapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeNDmBUyzGyG4c8_qwFcF5c3YYyUXNcoU',
    appId: '1:724636203630:web:3568d261db4f71857d847f',
    messagingSenderId: '724636203630',
    projectId: 'benevolentrealty-cfb1d',
    authDomain: 'benevolentrealty-cfb1d.firebaseapp.com',
    storageBucket: 'benevolentrealty-cfb1d.firebasestorage.app',
    measurementId: 'G-1L6EJY64BL',
  );
}
